[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/dist"

# Toutes les routes React Router doivent retomber sur index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
